name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: precise

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Temporarily disabling this step due to formatting issues.
      # Linter and prettier) currently throws numerous warnings.
      # Code style checks will be re-enabled in a future PR that includes a codebase reformat.
      # - name: Check code style
      #   run: npm run check:clean

      - name: Build package
        run: npm run package:clean
